spring.application.name=fashion-website

# Database
spring.datasource.url=jdbc:mariadb://localhost:3306/fashion-website
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8080

#key
jwt.signerKey=59a7cd85af4c99bea27a6518cbdb866000967e4170222736e641e209b482c9a0